FROM geoffh1977/chrony:latest AS chrony

# Uncomment to use custom config. The Docker file's
# automated settings seemed good enough on preliminary testing
# COPY time-sync/chrony.conf /etc/chrony.conf